option(ENABLE_TESTS "Enable building and running tests" ON)
option(ENABLE_WINDOWED_TESTS "Build tests that require a Vulkan runtime and display" OFF)
option(ENABLE_VULKAN_VALIDATION_LAYERS "Enable Vulkan Validation Layers" ON)
option(ENABLE_SAMPLE_MODEL_DOWNLOAD "Download pinned glTF Sample Models during asset generation" ON)
option(ENABLE_BIM_SAMPLE_MODEL_DOWNLOAD "Download latest buildingSMART IFC5-development files during asset generation" ON)
option(ENABLE_USD_SAMPLE_MODEL_DOWNLOAD "Download OpenUSD sample model archives during asset generation" ON)
option(ENABLE_TINYUSDZ_USD_LOADER "Build the TinyUSDZ-backed USD/USDZ importer" ON)
